blank_issues_enabled: false
contact_links:
  - name: 💬 Support via Discord
    url: https://discord.gg/seerr
    about: Chat with other users and the Seerr dev team
  - name: 🐛 Report an Issue
    url: https://github.com/binarygeek119/seerr/issues/new/choose
    about: Report bugs or request features on this fork
