blank_issues_enabled: false
contact_links:
  - name: 💬 Support via Discord
    url: https://discord.gg/xmNs5ecFX
    about: Chat with the Open Repository's community
  - name: 🐛 Report an Issue
    url: https://github.com/binarygeek119/seerr/issues/new/choose
    about: Report bugs or request features on this fork
